  METHOD convert_sovos.

    DATA(lv_json) = json.
    REPLACE ALL OCCURRENCES OF '"OBJETOS"' IN lv_json WITH '"objetos"'.
    REPLACE ALL OCCURRENCES OF 'KNW' IN lv_json WITH 'knw'.
    REPLACE ALL OCCURRENCES OF 'NOTAFISCALITEMLIST' IN lv_json WITH 'notaFiscalItemList'.
    REPLACE ALL OCCURRENCES OF '0150EMITENTE' IN lv_json WITH '0150Emitente'.
    REPLACE ALL OCCURRENCES OF '0150DESTINATARIO' IN lv_json WITH '0150Destinatario'.
    REPLACE ALL OCCURRENCES OF '0150TRANSPORTADOR' IN lv_json WITH '0150Transportador'.
    REPLACE ALL OCCURRENCES OF '"0.0"' IN lv_json WITH '0'.
    REPLACE ALL OCCURRENCES OF '"0 "' IN lv_json WITH '0'.
    REPLACE ALL OCCURRENCES OF 'VL_SERVICO1' IN lv_json WITH 'vl_SERVICO'.
    REPLACE ALL OCCURRENCES OF 'INTEGRACAONOTAFISCALSERVICO' IN lv_json WITH 'integracaoNotaFiscalServicoItemList'.

    ret = lv_json.

  ENDMETHOD.