  METHOD convert_sovos.

    DATA(lv_json) = json.
    REPLACE ALL OCCURRENCES OF '"OBJETOS"' IN lv_json WITH '"objetos"'.
    REPLACE ALL OCCURRENCES OF 'KNW' IN lv_json WITH 'knw'.
    REPLACE ALL OCCURRENCES OF 'NOTAFISCALITEMLIST' IN lv_json WITH 'notaFiscalItemList'.
    REPLACE ALL OCCURRENCES OF '0150EMITENTE' IN lv_json WITH '0150Emitente'.
    REPLACE ALL OCCURRENCES OF '0150DESTINATARIO' IN lv_json WITH '0150Destinatario'.
    REPLACE ALL OCCURRENCES OF '0150TRANSPORTADOR' IN lv_json WITH '0150Transportador'.
    REPLACE ALL OCCURRENCES OF '"0.0"' IN lv_json WITH '0'.
    REPLACE ALL OCCURRENCES OF '"0 "' IN lv_json WITH '0'.
    REPLACE ALL OCCURRENCES OF 'VL_SERVICO1' IN lv_json WITH 'vl_SERVICO'.
    REPLACE ALL OCCURRENCES OF 'INTEGRACAONOTAFISCALSERVICO' IN lv_json WITH 'integracaoNotaFiscalServicoItemList'.
    REPLACE ALL OCCURRENCES OF 'INTEGR_ITENS_CONSUM_LIST' IN lv_json WITH 'integracaoItensConsumidosList'.
    REPLACE ALL OCCURRENCES OF 'PRODUTOINSUMO' IN lv_json WITH 'ProdutoInsumo'.
    REPLACE ALL OCCURRENCES OF 'INTEGRACAOCONHECIMENTOTRANS' IN lv_json WITH 'integracaoConhecimentoTransporte'.
    "C110 / C113
    REPLACE ALL OCCURRENCES OF 'NOTAFISCALINFCOMPLEMENTARLIST' IN lv_json WITH 'notaFiscalInfComplementarList'.
    REPLACE ALL OCCURRENCES OF 'KNWC110' IN lv_json WITH 'knwC110'.
    REPLACE ALL OCCURRENCES OF 'INTEGRACAONOTAFISCREFLIST' IN lv_json WITH 'integracaoNotaFiscalReferenciadaList'.
    REPLACE ALL OCCURRENCES OF 'KNWC113' IN lv_json WITH 'knwC113'.
    ret = lv_json.

  ENDMETHOD.