CLASS /pyxs/sovos_types DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES:
      BEGIN OF ty_knwc100,
        dm_emitente            TYPE string,
        dm_entrada_saida       TYPE string,
        serie_subserie         TYPE string,
        nr_documento           TYPE string,
        dt_emissao_doc         TYPE string,
        dt_entrada             TYPE string,
        vl_total_mercad        TYPE p LENGTH 15 DECIMALS 2,
        vl_desconto            TYPE string,
        vl_frete               TYPE string,
        vl_seguro              TYPE string,
        vl_outras_desp         TYPE string,
        vl_ipi                 TYPE string,
        vl_icms_substit        TYPE string,
        vl_tot_n_fiscal        TYPE string,
        nr_insc_est_sub        TYPE string,
        dm_tipo_fatura         TYPE string,
        ds_observacao          TYPE string,
        cod_empresa            TYPE string,
        cod_filial             TYPE string,
        cd_modelo_doc          TYPE string,
        cd_pessoa_remet_dest   TYPE string,
        dm_modal_frete         TYPE string,
        cd_sit_documento       TYPE string,
        nr_chave_eletr         TYPE string,
        vl_abat_n_trib         TYPE string,
        nr_referencia          TYPE string,
        ds_ade                 TYPE string,
        cod_mun_orig           TYPE string,
        cod_mun_des            TYPE string,
        nr_cnpj_cpf_venda_cons TYPE string,
        ds_natureza            TYPE string,
        ds_uf_dest_emit        TYPE string,
        ds_ressarcimento       TYPE string,
        id_usuario_imp         TYPE string,
        vl_serv_nt             TYPE string,
        vl_bc_irrf             TYPE string,
        vl_irrf                TYPE string,
        vl_bc_prev             TYPE string,
        vl_prev                TYPE string,
        cd_mun_serv_prest      TYPE string,
        vl_material_terc       TYPE string,
        vl_sub_empr            TYPE string,
        dm_finalidade          TYPE string,
        dm_destinatario        TYPE string,
        chave_registro         TYPE string,
        vl_servico1            TYPE string,
      END OF ty_knwc100,

      BEGIN OF ty_knwc111,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        chave_registro     TYPE string,
        cd_pessoa_rem_dest TYPE string,
        nr_item            TYPE p LENGTH 15 DECIMALS 2,
        nr_processo        TYPE string,
        dm_processo        TYPE string,
      END OF ty_knwc111,

      BEGIN OF ty_knwc120,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        vl_ipi             TYPE p LENGTH 15 DECIMALS 2,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        chave_registro     TYPE string,
        vl_bc_icms         TYPE p LENGTH 15 DECIMALS 2,
        vl_icms            TYPE p LENGTH 15 DECIMALS 2,
        cd_pessoa_rem_dest TYPE string,
        vl_pis             TYPE p LENGTH 15 DECIMALS 2,
        vl_cofins          TYPE p LENGTH 15 DECIMALS 2,
        dt_registro        TYPE string,
        nr_di              TYPE string,
        dm_importacao      TYPE string,
        nr_acdraw          TYPE string,
        dt_desembaraco     TYPE string,
        vl_cif             TYPE p LENGTH 15 DECIMALS 2,
        vl_desp_aduan      TYPE p LENGTH 15 DECIMALS 2,
        vl_desp_ad_icms    TYPE p LENGTH 15 DECIMALS 2,
        vl_iof             TYPE p LENGTH 15 DECIMALS 2,
        vl_ii              TYPE p LENGTH 15 DECIMALS 2,
        vl_bc_ipi          TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc120,

      BEGIN OF ty_knwc140,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        chave_registro     TYPE string,
        ds_complementar    TYPE string,
        cd_pessoa_rem_dest TYPE string,
        dm_emitente_titulo TYPE string,
        dm_titulo          TYPE string,
        nr_titulo          TYPE string,
        qtde_parcela       TYPE p LENGTH 15 DECIMALS 2,
        vl_titulo          TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc140,

      BEGIN OF ty_knwc141,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        chave_registro     TYPE string,
        cd_pessoa_rem_dest TYPE string,
        vl_parcela         TYPE p LENGTH 15 DECIMALS 2,
        nr_parcela         TYPE p LENGTH 15 DECIMALS 2,
        dt_vencimento      TYPE string,
      END OF ty_knwc141,

      BEGIN OF ty_knwc197,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        chave_registro     TYPE string,
        aliq_icms          TYPE p LENGTH 15 DECIMALS 2,
        ds_complementar    TYPE string,
        cd_ref_53          TYPE string,
        cd_prod_serv       TYPE string,
        vl_bc_icms         TYPE p LENGTH 15 DECIMALS 2,
        vl_icms            TYPE p LENGTH 15 DECIMALS 2,
        vl_icms_outras     TYPE p LENGTH 15 DECIMALS 2,
        cd_pessoa_rem_dest TYPE string,
        nr_item            TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc197,

      BEGIN OF ty_knw0190,
        dt_inicial     TYPE string,
        dt_importacao  TYPE string,
        cod_empresa    TYPE string,
        cod_filial     TYPE string,
        id_usuario_imp TYPE string,
        chave_registro TYPE string,
        ds_unidade     TYPE string,
        ds_descricao   TYPE string,
      END OF ty_knw0190,

      BEGIN OF ty_knw0200,
        cd_plano_conta       TYPE string,
        dt_inicial           TYPE string,
        dt_importacao        TYPE string,
        cod_empresa          TYPE string,
        cod_filial           TYPE string,
        id_usuario_imp       TYPE string,
        chave_registro       TYPE string,
        cd_produto_serv      TYPE string,
        ds_produto_serv      TYPE string,
        unidade              TYPE string,
        cd_sit_tributar_icms TYPE string,
        aliq_icms            TYPE p LENGTH 15 DECIMALS 2,
        perc_red_ba_icms     TYPE p LENGTH 15 DECIMALS 2,
        dm_produto_venda     TYPE string,
        cd_lst               TYPE string,
        cd_ncm               TYPE string,
        cd_genero            TYPE string,
        dm_tipo_item         TYPE string,
        cd_331_ex_ipi        TYPE string,
        cd_barra             TYPE string,
        nr_cest              TYPE string,
        dm_origem_produto    TYPE string,
        cd_centro_custo      TYPE string,
        cd_sit_trib_ipi      TYPE string,
        cd_sit_trib_pis      TYPE string,
        cd_sit_trib_cofins   TYPE string,
        cd_nat_operacao      TYPE string,
        aliq_pis             TYPE p LENGTH 15 DECIMALS 2,
        aliq_cofins          TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knw0200,

      BEGIN OF ty_integracaonotafiscalajustel,
        knw0190 TYPE ty_knw0190,
        knw0200 TYPE ty_knw0200,
        knwc197 TYPE ty_knwc197,
      END OF ty_integracaonotafiscalajustel,

      BEGIN OF ty_knw0460,
        dt_inicial       TYPE string,
        dt_importacao    TYPE string,
        cod_empresa      TYPE string,
        cod_filial       TYPE string,
        id_usuario_imp   TYPE string,
        chave_registro   TYPE string,
        cod_grupoempresa TYPE string,
        dt_movimento     TYPE string,
        cd_obs           TYPE string,
        ds_obs           TYPE string,
        id               TYPE string,
      END OF ty_knw0460,

      BEGIN OF ty_knwc195,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        chave_registro     TYPE string,
        cd_0460            TYPE string,
        ds_complementar    TYPE string,
        cd_pessoa_rem_dest TYPE string,
        nr_item            TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc195,

      BEGIN OF ty_notafiscalobservacaolancame,
        knwc195                        TYPE ty_knwc195,
        knw0460                        TYPE ty_knw0460,
        integracaonotafiscalajustelist TYPE STANDARD TABLE OF ty_integracaonotafiscalajustel WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_notafiscalobservacaolancame,

      BEGIN OF ty_knwc113,
         dm_entrada_saida    TYPE string,
         serie_subserie      TYPE string,
         dm_emitente         TYPE string,
         nr_documento        TYPE string,
         dt_emissao_doc      TYPE string,
         cod_empresa         TYPE string,
         cod_filial          TYPE string,
         id_usuario_imp      TYPE string,
         nr_item             TYPE string,
         cd_pessoa_rem_dest  TYPE string,
         dm_entr_saida_refer TYPE string,
         dm_emitente_refer   TYPE string,
         cd_pessoa_refer     TYPE string,
         cd_modelo           TYPE string,
         serie_doc_refer     TYPE string,
         subser_doc_ref      TYPE string,
         nr_doc_refer        TYPE string,
         dt_doc_refer        TYPE string,
         nr_chave_refer      TYPE string,
       END OF ty_knwc113,

      BEGIN OF ty_knw0150,
        dt_inicial           TYPE string,
        dt_importacao        TYPE string,
        cod_empresa          TYPE string,
        cod_filial           TYPE string,
        id_usuario_imp       TYPE string,
        chave_registro       TYPE string,
        cd_pessoa            TYPE string,
        nm_razao_social      TYPE string,
        ds_endereco          TYPE string,
        ds_bairro            TYPE string,
        nr_cep               TYPE string,
        nr_cnpj_cpf          TYPE string,
        nr_inscr_est         TYPE string,
        nr_inscr_munic       TYPE string,
        nr_cei               TYPE string,
        nr_inscr_subst       TYPE string,
        cd_suframa           TYPE string,
        nr_numero            TYPE string,
        ds_complemento       TYPE string,
        nr_cep_cp            TYPE string,
        nr_cp                TYPE string,
        nr_fone              TYPE string,
        nr_fax               TYPE string,
        dm_relacionado       TYPE string,
        dt_ini_rel           TYPE string,
        dt_fin_rel           TYPE string,
        nr_nit               TYPE string,
        cd_cnae              TYPE string,
        nr_categoria         TYPE string,
        cd_municipio         TYPE string,
        cd_pais              TYPE string,
        ds_email             TYPE string,
        dm_natureza_empresa  TYPE string,
        dm_regime_tributario TYPE string,
        nm_tp_logradouro     TYPE string,
        nm_titulo_logradouro TYPE string,
        dm_contribuinte      TYPE string,
      END OF ty_knw0150,

      BEGIN OF ty_integracaoNotaFiscRefList,
        knw0150                        TYPE ty_knw0150,
        knwc113                        TYPE ty_knwc113,
      END OF ty_integracaoNotaFiscRefList,

      BEGIN OF ty_knwc110,
         dm_entrada_saida   TYPE string,
         serie_subserie     TYPE string,
         dm_emitente        TYPE string,
         nr_documento       TYPE string,
         dt_emissao_doc     TYPE string,
         cod_empresa        TYPE string,
         cod_filial         TYPE string,
         id_usuario_imp     TYPE string,
         ds_complementar    TYPE string,
         nr_item            TYPE string,
         cd_pessoa_rem_dest TYPE string,
         cd_ref_0450        TYPE string,
       END OF ty_knwc110,

      BEGIN OF ty_notaFiscalInfComplementarLi,
        knwc110                        TYPE ty_knwc110,
        integracaoNotaFiscRefList      TYPE STANDARD TABLE OF ty_integracaoNotaFiscRefList WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_notaFiscalInfComplementarLi,

      BEGIN OF ty_knwc170,
        vl_ii                TYPE string,
        vl_total_item        TYPE string,
        vl_desc_item         TYPE string,
        vl_contabil          TYPE string,
        dm_mov_fisica        TYPE string,
        cd_fiscal_oper       TYPE string,
        vl_ba_calc_icms      TYPE string,
        vl_icms_isento       TYPE string,
        vl_icms_outro        TYPE string,
        vl_icms_observ       TYPE string,
        vl_ba_calc_subs      TYPE string,
        aliq_icms_sub        TYPE string,
        dm_apur_ipi          TYPE string,
        cd_enq_ipi           TYPE string,
        vl_ba_calc_ipi       TYPE string,
        aliq_ipi             TYPE string,
        vl_ipi_isento        TYPE string,
        vl_ipi_outro         TYPE string,
        vl_ipi_observ        TYPE string,
        vl_ba_calc_pis       TYPE string,
        qtde_ba_calc_pis     TYPE string,
        vl_aliq_pis          TYPE string,
        vl_pis_subst         TYPE string,
        aliq_cof             TYPE string,
        dm_emitente          TYPE string,
        dm_entrada_saida     TYPE string,
        serie_subserie       TYPE string,
        nr_documento         TYPE string,
        dt_emissao_doc       TYPE string,
        vl_frete             TYPE string,
        vl_seguro            TYPE string,
        vl_outras_desp       TYPE string,
        vl_ipi               TYPE string,
        vl_icms_substit      TYPE string,
        cod_empresa          TYPE string,
        cod_filial           TYPE string,
        cd_plano_conta       TYPE string,
        cd_pessoa_rem_dest   TYPE string,
        cd_produto_serv      TYPE string,
        unidade              TYPE string,
        aliq_icms            TYPE string,
        nr_item              TYPE string,
        vl_icms              TYPE string,
        cd_sit_trib_ipi      TYPE string,
        cd_sit_trib_pis      TYPE string,
        cd_sit_trib_cofins   TYPE string,
        aliq_pis             TYPE string,
        vl_pis               TYPE string,
        qtde                 TYPE string,
        vl_unitario          TYPE string,
        cd_sit_trib_icms     TYPE string,
        vl_ba_calc_cof       TYPE string,
        qtde_ba_calc_cofins  TYPE string,
        vl_aliq_cofins       TYPE string,
        vl_cof               TYPE string,
        vl_cofins_subst      TYPE string,
        nr_cfi               TYPE string,
        vl_red_bc_icms       TYPE string,
        vl_bc_icms_uf_dest   TYPE string,
        aliq_icms_fcp        TYPE string,
        aliq_icms_dest       TYPE string,
        aliq_icms_inter      TYPE string,
        aliq_icms_inter_part TYPE string,
        vl_icms_fcp_dest     TYPE string,
        vl_icms_dest         TYPE string,
        vl_icms_rem          TYPE string,
        vl_bc_fcp_op         TYPE string,
        aliq_fcp_op          TYPE string,
        vl_fcp_op            TYPE string,
        vl_bc_fcp_st         TYPE string,
        aliq_fcp_st          TYPE string,
        vl_fcp_st            TYPE string,
        vl_bc_fcp_ret        TYPE string,
        aliq_fcp_ret         TYPE string,
        vl_fcp_ret           TYPE string,
        vl_abatimento_nt     TYPE string,
        vl_bc_iss            TYPE string,
        aliq_iss             TYPE string,
        vl_iss               TYPE string,
        vl_isentas_iss       TYPE string,
        vl_ded_bc_iss        TYPE string,
        vl_bc_iss_rt         TYPE string,
        vl_iss_rt            TYPE string,
        qtd_volume_total     TYPE string,
      END OF ty_knwc170,

      BEGIN OF ty_knw0220,
        cod_empresa    TYPE string,
        cod_filial     TYPE string,
        id_usuario_imp TYPE string,
        chave_registro TYPE string,
        cd_prod_serv   TYPE string,
        un_convertida  TYPE string,
        vl_fator_conv  TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knw0220,

      BEGIN OF ty_knw0400,
        dt_inicial       TYPE string,
        dt_importacao    TYPE string,
        cod_empresa      TYPE string,
        cod_filial       TYPE string,
        cod_grupoempresa TYPE string,
        dt_movimento     TYPE string,
        cd_fiscal        TYPE string,
        ds_cd_fiscal     TYPE string,
      END OF ty_knw0400,

      BEGIN OF ty_knw0500,
        dt_inicial      TYPE string,
        dm_tipo_conta   TYPE string,
        cd_plan_cta_tot TYPE string,
        ds_plano_conta  TYPE string,
        dm_natureza     TYPE string,
        dm_nivel        TYPE string,
        dt_importacao   TYPE string,
        id_ordem        TYPE p LENGTH 15 DECIMALS 2,
        cod_empresa     TYPE string,
        cod_filial      TYPE string,
        cd_plano_conta  TYPE string,
      END OF ty_knw0500,


      BEGIN OF ty_knwc176list,
        dm_emitente                  TYPE string,
        dm_entrada_saida             TYPE string,
        serie_subserie               TYPE string,
        nr_documento                 TYPE string,
        dt_emissao_doc               TYPE string,
        cod_empresa                  TYPE string,
        cod_filial                   TYPE string,
        id_usuario_imp               TYPE string,
        cd_pessoa_rem_dest           TYPE string,
        nr_item                      TYPE p LENGTH 15 DECIMALS 2,
        cd_mod_doc_ult               TYPE string,
        nr_doc_ult_ent               TYPE p LENGTH 15 DECIMALS 2,
        ser_sub_doc_ult              TYPE string,
        dt_ultima_ent                TYPE string,
        cd_pessoa_ult                TYPE string,
        qtde_ult_ent                 TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_ult_ent              TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_bc_subs              TYPE p LENGTH 15 DECIMALS 2,
        chave_nfe_ult_e              TYPE string,
        num_item_ult_e               TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_bc_icms_ult_e        TYPE p LENGTH 15 DECIMALS 2,
        aliq_icms_ult_e              TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_limite_bc_icms_ult_e TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_icms_ult_e           TYPE p LENGTH 15 DECIMALS 2,
        aliq_st_ult_e                TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_res                  TYPE p LENGTH 15 DECIMALS 2,
        cd_resp_ret                  TYPE string,
        cd_mot_res                   TYPE string,
        chave_nfe_ret                TYPE string,
        cd_part_nfe_ret              TYPE string,
        ser_nfe_ret                  TYPE string,
        num_nfe_ret                  TYPE p LENGTH 15 DECIMALS 2,
        item_nfe_ret                 TYPE p LENGTH 15 DECIMALS 2,
        cd_da                        TYPE string,
        nr_da                        TYPE string,
        vl_unit_res_fcp_st           TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc176list,


      BEGIN OF ty_knwc175list,
        dm_tipo_oper       TYPE string,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        cd_pessoa_rem_dest TYPE string,
        nr_item            TYPE p LENGTH 15 DECIMALS 2,
        nr_cnpj_conces     TYPE string,
        ds_uf_conces       TYPE string,
        nr_chassis         TYPE string,
      END OF ty_knwc175list,


      BEGIN OF ty_knwc173list,
        dt_validade        TYPE string,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        cd_pessoa_rem_dest TYPE string,
        nr_item            TYPE p LENGTH 15 DECIMALS 2,
        lote_medicam       TYPE string,
        vl_preco           TYPE p LENGTH 15 DECIMALS 2,
        dt_fabricacao      TYPE string,
        qtde_item          TYPE p LENGTH 15 DECIMALS 2,
        dm_referencia      TYPE string,
        dm_tipo_prod       TYPE string,
        vl_preco_tab       TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc173list,


      BEGIN OF ty_knwc171list,
        nr_tanque          TYPE string,
        dm_emitente        TYPE string,
        dm_entrada_saida   TYPE string,
        serie_subserie     TYPE string,
        nr_documento       TYPE string,
        dt_emissao_doc     TYPE string,
        cod_empresa        TYPE string,
        cod_filial         TYPE string,
        id_usuario_imp     TYPE string,
        cd_pessoa_rem_dest TYPE string,
        nr_item            TYPE p LENGTH 15 DECIMALS 2,
        qtde               TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc171list,

      BEGIN OF ty_knwc180,
        dm_emitente                TYPE string,
        dm_entrada_saida           TYPE string,
        serie_subserie             TYPE string,
        nr_documento               TYPE string,
        dt_emissao_doc             TYPE string,
        cod_empresa                TYPE string,
        cod_filial                 TYPE string,
        id_usuario_imp             TYPE string,
        cd_pessoa_rem_dest         TYPE string,
        nr_item                    TYPE p LENGTH 15 DECIMALS 2,
        dm_resp_ret_ent            TYPE string,
        qtde_item_ent              TYPE p LENGTH 15 DECIMALS 2,
        cd_unidade_ent             TYPE string,
        vl_unitario_ent            TYPE p LENGTH 15 DECIMALS 2,
        vl_unitario_icms_ent       TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_bc_icms_st_ent     TYPE p LENGTH 15 DECIMALS 2,
        vl_unitario_icms_st_ent    TYPE p LENGTH 15 DECIMALS 2,
        vl_unitario_fcp_st_ent     TYPE p LENGTH 15 DECIMALS 2,
        dm_da_ent                  TYPE string,
        nr_da_ent                  TYPE string,
        cd_mot_ret_sai             TYPE string,
        qtde_item_sai              TYPE p LENGTH 15 DECIMALS 2,
        cd_unidade_sai             TYPE string,
        vl_unitario_sai            TYPE p LENGTH 15 DECIMALS 2,
        vl_unitario_icms_sai       TYPE p LENGTH 15 DECIMALS 2,
        vl_unitario_icms_op_sai    TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_bc_icms_st_est_sai TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_icms_st_est_sai    TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_fcp_icms_st_sai    TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_icms_st_rest_sai   TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_fcp_st_rest_sai    TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_icms_st_compl_sai  TYPE p LENGTH 15 DECIMALS 2,
        vl_unit_fcp_st_compl_sai   TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_knwc180,

      BEGIN OF ty_integracaosfunidadeconversa,
        knw0220 TYPE ty_knw0220,
        knw0190 TYPE ty_knw0190,
      END OF ty_integracaosfunidadeconversa,

      BEGIN OF ty_notafiscalitemlist,
        knwc170              TYPE ty_knwc170,
        knw0190              TYPE ty_knw0190,
        knw0200              TYPE ty_knw0200,
        unidadeconversaolist TYPE STANDARD TABLE OF ty_integracaosfunidadeconversa WITH NON-UNIQUE DEFAULT KEY,
        knw0400              TYPE ty_knw0400,
        knw0500              TYPE ty_knw0500,
        nwc171list           TYPE STANDARD TABLE OF ty_knwc171list WITH NON-UNIQUE DEFAULT KEY,
        knwc173list          TYPE STANDARD TABLE OF ty_knwc173list WITH NON-UNIQUE DEFAULT KEY,
        knwc175list          TYPE STANDARD TABLE OF ty_knwc175list WITH NON-UNIQUE DEFAULT KEY,
        knwc176list          TYPE STANDARD TABLE OF ty_knwc176list WITH NON-UNIQUE DEFAULT KEY,
        knwc180              TYPE ty_knwc180,
      END OF ty_notafiscalitemlist,

      BEGIN OF ty_knwd700,
        dt_importacao     TYPE string,
        cod_empresa       TYPE string,
        cod_filial        TYPE string,
        id_usuario_imp    TYPE string,
        vl_servico        TYPE string,
        nr_subserie       TYPE string,
        vl_servico_nt     TYPE string,
        vl_terceiros      TYPE string,
        vl_desp_acessoria TYPE string,
        vl_deducoes       TYPE string,
        dm_tipo_assinante TYPE string,
        cd_conta_contabil TYPE string,
        dm_fin_doce       TYPE string,
        dm_tip_fat        TYPE string,
        cd_modelo_ref     TYPE string,
        nr_chv_doce_ref   TYPE string,
        hash_doc_ref      TYPE string,
        ser_doc_ref       TYPE string,
        num_doc_ref       TYPE string,
        mes_doc_ref       TYPE string,
        dm_ind_prepago    TYPE string,
        dm_ind_receita    TYPE string,
      END OF ty_knwd700,

      BEGIN OF ty_knwd100,
        id_empresa              TYPE p LENGTH 15 DECIMALS 2,
        dm_emitente             TYPE string,
        dt_importacao           TYPE string,
        nr_documento            TYPE string,
        dt_entrada              TYPE string,
        vl_icms                 TYPE p LENGTH 15 DECIMALS 2,
        nr_serie                TYPE string,
        dt_aquisicao_prestacao  TYPE string,
        nr_chave_acesso_cte     TYPE string,
        vl_total_documento      TYPE string,
        vl_total_desconto       TYPE p LENGTH 15 DECIMALS 2,
        vl_total_prest_servico  TYPE p LENGTH 15 DECIMALS 2,
        vl_nao_trbutado         TYPE p LENGTH 15 DECIMALS 2,
        dt_emissao              TYPE string,
        vl_base_calculo_icms    TYPE p LENGTH 15 DECIMALS 2,
        nr_chave_acesso_cte_ref TYPE string,
      END OF ty_knwd100,

      BEGIN OF ty_integracaoconhecimentotrans,
        knwd100 TYPE ty_knwd100,
      END OF ty_integracaoconhecimentotrans,

      BEGIN OF ty_objetos,
        knwc100                     TYPE ty_knwc100,
        knw0150destinatario         TYPE ty_knw0150,
        knw0150emitente             TYPE ty_knw0150,
        knw0150transportador        TYPE ty_knw0150,
        notaFiscalInfComplementarList TYPE STANDARD TABLE OF ty_notaFiscalInfComplementarLi WITH NON-UNIQUE DEFAULT KEY,
        knwc111                     TYPE ty_knwc111,
        knwc120                     TYPE ty_knwc120,
        knwc140                     TYPE ty_knwc140,
        knwc141                     TYPE STANDARD TABLE OF ty_knwc141 WITH NON-UNIQUE DEFAULT KEY,
        notafiscalitemlist          TYPE STANDARD TABLE OF ty_notafiscalitemlist WITH NON-UNIQUE DEFAULT KEY,
        obslancamentofiscallist     TYPE STANDARD TABLE OF ty_notafiscalobservacaolancame WITH NON-UNIQUE DEFAULT KEY,
        knwd700                     TYPE ty_knwd700,
        integracaoconhecimentotrans TYPE ty_integracaoconhecimentotrans,
        dm_ressarcimento            TYPE string,
      END OF ty_objetos,

      BEGIN OF ty_main,
        docnum  TYPE string,
        objetos TYPE STANDARD TABLE OF ty_objetos WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_main.



